question_data = [
    {"text": 'shakespeare isminin anlamı mızraklı asker demektir.', "answer": "True"},
    {"text": 'töre ve torah aynı köktendir.', "answer": "True"},
    {"text": 'jack ismi ile ceket kelimesi aynı kökten gelir.', "answer": "True"},
    {"text": 'yidişçe aramicenin eski adıdır.', "answer": "False"},
    {"text": 'lord ile lady aynı köktendir.', "answer": "True"},
    {"text": 'ki bağlacı arapçadan gelmedir.', "answer": "False"},
    {"text": 'mahzen türkçe kökenlidir.', "answer": "False"},
    {"text": 'sudan denizler ülkesi demektir', "answer": "False"},
    {"text": 'cypher ve şifre aynı kökten gelir', "answer": "True"},
    {"text": 'tayfun çinceden gelmedir', "answer": "True"},
    {"text": 'felek hititçeden gelmedir.', "answer": "False"},
    {"text": 'tekir rumca kaplan demektir {tiger}', "answer": "True"},
    {"text": 'imparator yunanca kökenlidir', "answer": "False"},
    {"text": 'incil {eu+angelos} müjde anlamına gelir', "answer": "True"},
    {"text": 'piyanoda 88 tuş vardır', "answer": "True"},
]
